#!/usr/bin/python
# -*- encoding: utf-8 -*-

import termbox
import sys
import logging as log
import menu

log.basicConfig(filename='dev.log', level=log.DEBUG)


def size(t):
    return (t.width(), t.height())


def draw(t, grid, full=True):
    if full:
        w, h = size(t)
        # assert(len(grid) == h)
        for line in grid:
            assert(len(line) == w)

    for height, line in enumerate(grid):
        for width, cell in enumerate(line):
            char, fg, bg = cell
            if fg is None:
                fg = termbox.WHITE
            if bg is None:
                bg = termbox.BLACK

            t.change_cell(width, height, char, fg, bg)
    t.present()


def defaultKeyHandler(event, menu):
    (event_type, ch, key, mod, w, h, x, y) = event
    if event_type == termbox.EVENT_KEY:
        if key == termbox.KEY_ARROW_DOWN:
            menu.move_down()
        elif key == termbox.KEY_ARROW_UP:
            menu.move_up()

        elif key == termbox.KEY_ENTER:
            return menu.selected
        elif key == termbox.KEY_ESC:
            sys.exit()
        else:
            log.debug("key not found")


def defaultMouseHandler(event, menu):
    pass


def start(input, Menu, keyHandler=None, mouseHandler=None):
    with termbox.Termbox() as t:
        menu = Menu(input, size(t))
        draw(t, menu.grid())
        while True:
            event = t.poll_event()
            while event:
                (type, ch, key, mod, w, h, x, y) = event

                if type == termbox.EVENT_RESIZE:
                    log.debug("redraw")
                    menu.grid_size = size(t)
                    draw(t, menu.grid())

                if type == termbox.EVENT_KEY:
                    if not(keyHandler):
                        keyHandler = defaultKeyHandler

                    out = keyHandler(event, menu)
                    if out:
                        return out

                if type == termbox.EVENT_MOUSE:
                    if not(keyHandler):
                        mouseHandler = defaultMouseHandler

                    out = mouseHandler(event, menu)
                    if out:
                        return out

                event = t.peek_event()

            draw(t, menu.grid())

    return ""


def main():
    input = [line.strip() for line in sys.stdin]

    m = menu.ListMenu
    print(start(input, m))


if __name__ == "__main__":
    main()
